const ON_REMOVE_WORD = 'ON_REMOVE_WORD';
const ON_TOGGLE_WORD = 'ON_TOGGLE_WORD';
const ON_ADD_WORD = 'ON_ADD_WORD';
const ON_TOGGLE_FORM = 'ON_TOGGLE_FORM';
const ON_SET_FILTER_MODE = 'ON_SET_FILTER_MODE';
const ON_LOADING = 'ON_LOADING';

const FETCH_DATA_WORDS = 'FETCH_DATA_WORDS';

export default {
  ON_REMOVE_WORD,
  ON_TOGGLE_WORD,
  ON_ADD_WORD,
  ON_TOGGLE_FORM,
  ON_SET_FILTER_MODE,
  FETCH_DATA_WORDS,
  ON_LOADING,
};
